# Generated by Django 4.2.14 on 2024-08-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YogaStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_class_style', models.CharField(choices=[('REST', 'Restorative Yoga'), ('YIN', 'Yin Yoga'), ('GENTLE', 'Gentle Yoga'), ('BEGINNERS', "Beginners' Yoga"), ('FLOW1', 'Yoga Flow Level 1'), ('FLOW2', 'Yoga Flow Level 2'), ('MIXED', 'Yoga Flow Mixed Level'), ('EXPRESS', 'Express Lunchtime Yoga')], default='MIXED', max_length=10)),
            ],
        ),
    ]
