# Generated by Django 4.2.14 on 2024-08-10 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0003_groupclass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupclass',
            options={'verbose_name_plural': 'GroupClasses'},
        ),
        migrations.AddField(
            model_name='styledescription',
            name='style',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.yogastyle'),
        ),
        migrations.RemoveField(
            model_name='groupclass',
            name='description',
        ),
        migrations.RemoveField(
            model_name='groupclass',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='groupclass',
            name='title',
        ),
        migrations.AddField(
            model_name='groupclass',
            name='description',
            field=models.ManyToManyField(to='schedule.styledescription'),
        ),
        migrations.AddField(
            model_name='groupclass',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupclass',
            name='title',
            field=models.ManyToManyField(to='schedule.yogastyle'),
        ),
    ]
