# Generated by Django 4.2.14 on 2024-08-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_groupclass_location_groupclass_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styledescription',
            name='group_class_description',
            field=models.TextField(blank=True, choices=[('Restorative yoga is a slow, gentle practice using props ', 'Restorative description'), ('Yin Yoga is a perfect complement to the dynamic and muscular ', 'Yin description'), ('Gentle Yoga Flow is a unique sequence of movements and postures ', 'Gentle description'), ("The beginners' yoga class is a great way to start your ", "Beginners' description"), ('This class is suitable for complete beginners and students who want ', 'Flow 1 description'), ('You will need a yoga foundation, this class is for those ', 'Flow 2 description'), ('The mixed-level class is designed to take you deeper into ', 'Flow Mixed description'), ('Make the most of your lunch break with an invigorating and ', 'Express description'), ('During pregnancy your body goes through many changes, which ', 'Prenatal description')], null=True),
        ),
        migrations.AlterField(
            model_name='yogastyle',
            name='group_class_style',
            field=models.CharField(blank=True, choices=[('Restorative Yoga', 'REST'), ('Yin Yoga', 'YIN'), ('Gentle Yoga', 'GENTLE'), ("Beginners' Yoga", 'BEGINNERS'), ('Yoga Flow Level 1', 'FLOW1'), ('Yoga Flow Level 2', 'FLOW2'), ('Yoga Flow Mixed Level', 'MIXED'), ('Express Lunchtime Yoga', 'EXPRESS'), ('Prenatal Yoga', 'PRENATAL')], max_length=30, null=True),
        ),
    ]
