# Generated by Django 4.2.14 on 2024-08-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_alter_styledescription_group_class_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupclass',
            name='duration',
            field=models.CharField(choices=[('45 minutes', '45 minutes'), ('60 minutes', '60 minutes')], default='60 minutes'),
        ),
        migrations.AlterField(
            model_name='groupclass',
            name='location',
            field=models.CharField(choices=[('Studio 1', 'Studio 1'), ('Studio 2', 'Studio 2')], default='Studio 1'),
        ),
        migrations.AlterField(
            model_name='groupclass',
            name='start_time',
            field=models.CharField(blank=True, choices=[('7.30 am', '7.30'), ('9 am', '9.00'), ('10 am', '10.00'), ('11 am', '11.00'), ('1.05 pm', '13.05'), ('6 pm', '18.00'), ('6.30 pm', '18.30'), ('7.15 pm', '19.15'), ('7.30 pm', '19.30')], max_length=10, null=True),
        ),
    ]
