# Generated by Django 4.2.14 on 2024-08-20 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_alter_booking_chosen_class_alter_booking_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='chosen_class',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.groupclass'),
        ),
    ]
