# Generated by Django 4.2.14 on 2024-08-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0020_alter_booking_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='waiver_signed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
