# Generated by Django 4.2.14 on 2024-09-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0026_repeatedevent_eventoccurrence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupclass',
            name='duration',
        ),
        migrations.AddField(
            model_name='groupclass',
            name='duration_mins',
            field=models.IntegerField(choices=[(45, 45), (60, 60)], default=60),
        ),
    ]
