# Generated by Django 4.2.14 on 2024-09-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0027_remove_groupclass_duration_groupclass_duration_mins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='class_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='class_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
