# Generated by Django 4.2.14 on 2024-09-18 09:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0028_remove_booking_class_date_booking_class_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='SpecificGroupClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('specific_title', models.CharField(blank=True, max_length=30, null=True)),
                ('specific_datetime', models.DateTimeField(blank=True, null=True)),
                ('num_of_participants', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)])),
                ('participants_names', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-specific_datetime'],
            },
        ),
    ]
