# Generated by Django 4.2.14 on 2024-09-19 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0029_alter_booking_booking_time_specificgroupclass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupclass',
            options={'ordering': ['first_class__week_day', 'start_time'], 'verbose_name_plural': 'Group classes'},
        ),
        migrations.AlterModelOptions(
            name='specificgroupclass',
            options={'ordering': ['-specific_datetime'], 'verbose_name_plural': 'Specific group classes'},
        ),
    ]
