# Generated by Django 4.2.14 on 2024-09-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0030_alter_groupclass_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('class full', 'class full'), ("client's decision", "client's decision")], null=True),
        ),
    ]
