# Generated by Django 4.2.14 on 2024-09-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0033_remove_groupclass_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('class full', 'class full'), ("client's decision", "client's decision")], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='groupclass',
            name='location',
            field=models.CharField(choices=[('Studio 1', 'Studio 1'), ('Studio 2', 'Studio 2')], default='Studio 1', max_length=20),
        ),
    ]
