# Generated by Django 4.2.14 on 2024-10-02 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupclass',
            name='participants',
        ),
    ]
