# Generated by Django 4.2.14 on 2024-08-10 19:59

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0002_styledescription_alter_yogastyle_group_class_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(blank=True, choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=10, null=True)),
                ('start_time', models.CharField(blank=True, choices=[('7.30', '7.30 am'), ('9.00', '9 am'), ('10.00', '10 am'), ('11.00', '11 am'), ('13.05', '1.05 pm'), ('18.00', '6 pm'), ('18.30', '6.30 pm'), ('19.15', '7.15 pm'), ('19.30', '7.30 pm')], max_length=10, null=True)),
                ('duration', models.IntegerField(choices=[(45, '45 minutes'), (60, '60 minutes')], default=60)),
                ('image', cloudinary.models.CloudinaryField(default='../static/images/down_dog.jpg', max_length=255, verbose_name='image')),
                ('description', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='class_description', to='schedule.styledescription')),
                ('participants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_class_clients', to=settings.AUTH_USER_MODEL)),
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_class_title', to='schedule.yogastyle')),
            ],
        ),
    ]
