# Generated by Django 4.2.14 on 2024-10-02 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_groupclass_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specificgroupclass',
            options={'ordering': ['-specific_datetime'], 'verbose_name_plural': 'specific group classes'},
        ),
    ]
