# Generated by Django 4.2.14 on 2024-10-06 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_specificgroupclass_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupclass',
            options={'ordering': ['first_class__week_day', 'first_class__time'], 'verbose_name_plural': 'group classes'},
        ),
    ]
