# Generated by Django 4.2.14 on 2024-08-11 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0005_remove_groupclass_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupclass',
            name='location',
            field=models.IntegerField(choices=[(1, 'Studio 1'), (2, 'Studio 2')], default=1),
        ),
        migrations.AddField(
            model_name='groupclass',
            name='teacher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='groupclass',
            name='participants',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='styledescription',
            name='group_class_description',
            field=models.TextField(choices=[('Restorative yoga is a slow, gentle practice using props ', 'Restorative description'), ('Yin Yoga is a perfect complement to the dynamic and muscular ', 'Yin description'), ('Gentle Yoga Flow is a unique sequence of movements and postures ', 'Gentle description'), ("The beginners' yoga class is a great way to start your ", "Beginners' description"), ('This class is suitable for complete beginners and students who want ', 'Flow 1 description'), ('You will need a yoga foundation, this class is for those ', 'Flow 2 description'), ('The mixed-level class is designed to take you deeper into ', 'Flow Mixed description'), ('Make the most of your lunch break with an invigorating and ', 'Express description'), ('During pregnancy your body goes through many changes, which ', 'Prenatal description')], default='The mixed-level class is designed to take you deeper into '),
        ),
    ]
