# Generated by Django 4.2.14 on 2024-08-19 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0014_alter_styledescription_group_class_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='chosen_class',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked_class', to='schedule.groupclass'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
