# Generated by Django 4.2.14 on 2024-08-22 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_alter_booking_chosen_class_alter_booking_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupclass',
            options={'ordering': ['weekday', 'start_time'], 'verbose_name_plural': 'GroupClasses'},
        ),
        migrations.AddField(
            model_name='groupclass',
            name='capacity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(16)]),
        ),
    ]
