# Generated by Django 4.2.14 on 2024-08-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0021_booking_waiver_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupclass',
            name='teacher_bio',
            field=models.CharField(blank=True, choices=[('Mary is +500-hour qualified yoga teacher. She teaches yoga with an emphasis on safety and alignment. This offers students a supportive environment to explore their personal yoga practice. Mary began practising yoga in 2012. Her interest derived from the desire to balance out a busy lifestyle. Finding a new level of stillness, she is now on a mission to share the benefits of yoga with everyone! She will continue her mission by going to training and events to improve her teaching skills.', "Mary's bio"), ("Joanne's approach to teaching yoga is very much like her approach to life - full of curiosity, gentleness, and playfulness. 2014 was the beginning of her journey into a deeper understanding of herself, and this brought her to Goa, India where she completed her 200hr Yoga teacher training in 2017, and returning again in 2018 to Rishikesh to complete 100 hours of Yin, breathwork and Meditation training. Joanne's teaching style is non-judgemental and focused on helping to foster the student's unique relationship with yoga and their own bodies. She uses the fluidity of vinyasa to help awaken and inspire this connection to ourselves and to the world around us.", "Joanne's bio")], max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='groupclass',
            name='teacher',
            field=models.CharField(blank=True, choices=[('Mary Dawson', 'Mary Dawson'), ('Joanne West', 'Joanne West')], max_length=100, null=True),
        ),
    ]
