# Generated by Django 4.2.14 on 2024-08-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0023_booking_booking_cancelled_groupclass_first_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupclass',
            name='weekday',
            field=models.CharField(blank=True, choices=[('Mon', '1 Monday'), ('Tue', '2 Tuesday'), ('Wed', '3 Wednesday'), ('Thu', '4 Thursday'), ('Fri', '5 Friday'), ('Sat', '6 Saturday'), ('Sun', '7 Sunday')], max_length=10, null=True),
        ),
    ]
