# Generated by Django 4.2.14 on 2024-08-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0024_alter_groupclass_weekday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupclass',
            options={'ordering': ['first_class__week_day', 'start_time'], 'verbose_name_plural': 'GroupClasses'},
        ),
        migrations.AlterField(
            model_name='groupclass',
            name='weekday',
            field=models.CharField(blank=True, choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=10, null=True),
        ),
    ]
