# Generated by Django 4.2.14 on 2024-09-03 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0027_remove_groupclass_duration_groupclass_duration_mins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='class_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='class_datetime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.eventoccurrence'),
        ),
    ]
