# Generated by Django 4.2.14 on 2024-09-17 10:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0028_remove_booking_class_date_booking_class_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='SpecificGroupClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('num_of_participants', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)])),
                ('participants_list', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('specific_datetime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_datetime', to='schedule.booking')),
                ('specific_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_title', to='schedule.booking')),
            ],
            options={
                'ordering': ['-specific_datetime'],
            },
        ),
    ]
