# Generated by Django 4.2.14 on 2024-09-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0029_alter_booking_booking_time_specificgroupclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificgroupclass',
            name='specific_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
