# Generated by Django 4.2.14 on 2024-09-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0030_alter_specificgroupclass_specific_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificgroupclass',
            name='specific_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
