# Generated by Django 4.2.14 on 2024-09-20 15:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0031_booking_cancellation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupclass',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
