# Generated by Django 4.2.14 on 2024-08-07 09:04

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('injuries', models.TextField(blank=True, max_length=300)),
                ('profile_pic', cloudinary.models.CloudinaryField(default='../static/images/default_profile_pic.jpg', max_length=255, verbose_name='image')),
                ('signed_waiver', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
