# Generated by Django 4.2.14 on 2024-08-04 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_user_profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='client_user_profile',
            name='last_name',
        ),
    ]
